spring.application.name=Xanadu Wars

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.schema_validation=false
