spring.application.name=Xanadu Wars

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.schema_validation=false
spring.jpa.open-in-view=false

xanadu.auth.jwt.signing-key-bonus-duration=PT5M
xanadu.auth.jwt.access-token-duration=PT1H
xanadu.auth.jwt.refresh-token-short-duration=PT12H
xanadu.auth.jwt.refresh-token-long-duration=PT336H
xanadu.auth.jwt.magic-link-duration=PT14H

xanadu.core.ruleset.root=version
